# Generated by Django 2.0.2 on 2018-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usr_fecha_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'PED_FORMACION_ACADEMICA',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usr_fecha_edicion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'PED_PERFIL',
            },
        ),
        migrations.CreateModel(
            name='PerfilPrivilegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=True, to='usuario.Perfil')),
            ],
            options={
                'db_table': 'PED_PERFIL_PRIVILEGIO',
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usr_fecha_edicion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'PED_PRIVILEGIO',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('expiration_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=200)),
                ('ape_pat', models.CharField(max_length=100)),
                ('ape_mat', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ubigeo', models.CharField(max_length=6)),
                ('estado', models.IntegerField()),
                ('perfil', models.ForeignKey(on_delete=True, to='usuario.Perfil')),
            ],
            options={
                'db_table': 'PED_USUARIO',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='usuario',
            field=models.ForeignKey(on_delete=True, related_name='tokens', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='privilegio',
            name='usr_creacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_privilegio_usr_created', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='privilegio',
            name='usr_modificacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_privilegio_usr_modified', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='perfilprivilegio',
            name='privilegio',
            field=models.ForeignKey(on_delete=True, to='usuario.Privilegio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='privilegios',
            field=models.ManyToManyField(through='usuario.PerfilPrivilegio', to='usuario.Privilegio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usr_creacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_perfil_usr_created', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usr_modificacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_perfil_usr_modified', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='usr_creacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_formacionacademica_usr_created', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='usr_modificacion',
            field=models.ForeignKey(on_delete=True, related_name='usuario_formacionacademica_usr_modified', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='usuario',
            field=models.ForeignKey(on_delete=True, to='usuario.Usuario'),
        ),
    ]
